# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a47a22f612de1140ba602e7ec5372cb24ed883c164a79d88f16a10f600380a50d7e286c23651e74810ac96a1001aef03aa40501a5cd2abc698e7f12c6d0a7ee8

test:
  secret_key_base: a2b49735a491ef674ea8b2f832962e4e6857417f3ad6f51a845d6015826b09027680466d19731b102e0b2c1e0f325939d8c096a57aaac9596477c8d79d0af9ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
